# Generated by Django 5.2.8 on 2025-12-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_dailyoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyoperation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
