# Generated by Django 5.2.8 on 2025-12-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_dailyoperation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyoperation',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='dailyoperation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dailyoperation',
            name='opened_by',
        ),
    ]
