# Generated by Django 5.2.8 on 2025-12-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_remove_dailyoperation_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyoperation',
            name='is_open',
            field=models.BooleanField(),
        ),
    ]
