# Generated by Django 5.2.8 on 2025-12-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_dailyoperation_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyoperation',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
