# Generated by Django 5.2.8 on 2025-12-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_dailyoperation_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.DeleteModel(
            name='DailyOperation',
        ),
    ]
