# Generated by Django 5.2.8 on 2025-12-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_operationsession_delete_dailyoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de ventas',
                'verbose_name_plural': 'Estado de ventas',
            },
        ),
        migrations.DeleteModel(
            name='OperationSession',
        ),
    ]
