# Generated by Django 5.2.8 on 2025-12-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_salesstate_delete_operationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
