# Generated by Django 5.2.8 on 2025-12-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_venta_iva_venta_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='subtotal',
        ),
    ]
