# Generated by Django 5.2.8 on 2025-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_venta_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
