# Generated by Django 5.2.8 on 2025-12-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_venta_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(default='boleta', max_length=20),
        ),
    ]
