# Generated by Django 5.2.8 on 2025-12-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_venta_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
