# Generated by Django 5.2.8 on 2025-12-08 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_alter_venta_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_boleta', models.CharField(max_length=20, unique=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='boleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.boleta'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('razon_social', models.CharField(max_length=200)),
                ('giro', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.factura'),
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
