# Generated by Django 5.2.8 on 2025-12-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jefe venta', 'Jefe venta'), ('vendedor', 'Vendedor')], default='admin', max_length=20),
        ),
    ]
