# Generated by Django 5.2.8 on 2025-12-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jefe venta', 'Jefe venta'), ('vendedor', 'Vendedor')], default='jefe venta', max_length=20),
        ),
    ]
